# Generated by Django 2.2.12 on 2020-06-22 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryHand', models.CharField(default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('specialProperties', models.TextField(blank=True)),
                ('specialName', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(choices=[('F', 'Fine'), ('D', 'Diminutive'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='M', max_length=1)),
                ('weight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('abilities', models.ForeignKey(on_delete='CASCADE', to='player.Abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subclass', models.CharField(blank=True, default='', max_length=100)),
                ('acPenalty', models.BooleanField(default=False)),
                ('untrained', models.BooleanField()),
                ('ability', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('effect', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.Item')),
                ('damage', models.CharField(max_length=10)),
                ('extraDamage', models.IntegerField()),
                ('ammountPerWeight', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('player.item',),
        ),
        migrations.CreateModel(
            name='WearableItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.Item')),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('player.item',),
        ),
        migrations.CreateModel(
            name='WieldableItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.Item')),
                ('area', models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('player.item',),
        ),
        migrations.CreateModel(
            name='selectedRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliedAbilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Abilities')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Race')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='specialAbilities',
            field=models.ManyToManyField(blank=True, to='player.SpecialAbilities'),
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('abilities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Abilities')),
                ('activeEffects', models.ManyToManyField(blank=True, to='player.ActiveEffect')),
                ('equipment', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player.Equipment')),
                ('inventory', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player.Inventory')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.selectedRace')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowsSpecialProperties', models.BooleanField()),
                ('knowsSpecialName', models.BooleanField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Item')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Location'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armors', to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='carriedEquipment',
            field=models.ManyToManyField(blank=True, to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='leftHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leftHanded', to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rightHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='righthanded', to='player.InventoryItem'),
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('abilities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Abilities')),
            ],
        ),
        migrations.AddField(
            model_name='activeeffect',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Effect'),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('wearableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.WearableItem')),
                ('ac', models.IntegerField()),
                ('arcaneFailure', models.IntegerField()),
                ('maxDex', models.IntegerField()),
                ('ACPenalty', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('player.wearableitem',),
        ),
        migrations.CreateModel(
            name='PCSkillRank',
            fields=[
                ('skillrank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.SkillRank')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.PC')),
            ],
            bases=('player.skillrank',),
        ),
        migrations.CreateModel(
            name='MagicalItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.Item')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Spell')),
            ],
            options={
                'abstract': False,
            },
            bases=('player.item',),
        ),
        migrations.CreateModel(
            name='EffectSkillRank',
            fields=[
                ('skillrank_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.SkillRank')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Effect')),
            ],
            bases=('player.skillrank',),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('armor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.Armor')),
                ('hands', models.CharField(choices=[('1H', 'One Handed')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('player.armor',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('wieldableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.WieldableItem')),
                ('blunt', models.BooleanField()),
                ('pierce', models.BooleanField()),
                ('slash', models.BooleanField()),
                ('damage', models.CharField(max_length=9)),
                ('criticalRange', models.IntegerField()),
                ('critical', models.IntegerField()),
                ('ranged', models.BooleanField()),
                ('range', models.IntegerField()),
                ('hands', models.IntegerField()),
                ('defualtAmmo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Ammo')),
            ],
            options={
                'abstract': False,
            },
            bases=('player.wieldableitem',),
        ),
        migrations.CreateModel(
            name='AmmoBundle',
            fields=[
                ('wieldableitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='player.WieldableItem')),
                ('quantity', models.IntegerField()),
                ('ammo', models.ManyToManyField(to='player.Ammo')),
            ],
            options={
                'abstract': False,
            },
            bases=('player.wieldableitem',),
        ),
    ]
