# Generated by Django 2.2.12 on 2020-06-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CG', 'Chaotic Good'), ('CE', 'Chaotic Evil'), ('NN', 'True Neutral'), ('NG', 'Neutral Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('LG', 'Lawful Good'), ('CN', 'Chaotic Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('EYE', 'Eye'), ('FEET', 'Feet'), ('LEGS', 'Legs'), ('TORSO', 'Torso'), ('HEAD', 'Head'), ('NECK', 'Neck')], max_length=50),
        ),
    ]
