# Generated by Django 2.2.12 on 2020-06-26 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CE', 'Chaotic Evil'), ('LG', 'Lawful Good'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('NN', 'True Neutral'), ('LN', 'Lawful Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Location'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('NECK', 'Neck'), ('FEET', 'Feet'), ('LEGS', 'Legs'), ('HEAD', 'Head'), ('EYE', 'Eye'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
