# Generated by Django 2.2.12 on 2020-06-22 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200622_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='inventory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='player.Inventory'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
    ]
