# Generated by Django 2.2.12 on 2020-07-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200702_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='classLevels',
        ),
        migrations.AddField(
            model_name='playerclasslevel',
            name='pc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='player.PC'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CN', 'Chaotic Neutral'), ('NG', 'Neutral Good'), ('LG', 'Lawful Good'), ('CG', 'Chaotic Good'), ('NE', 'Neutral Evil'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('CE', 'Chaotic Evil'), ('LN', 'Lawful Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('NECK', 'Neck'), ('HEAD', 'Head'), ('LEGS', 'Legs'), ('EYE', 'Eye'), ('FEET', 'Feet'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
