# Generated by Django 2.2.12 on 2020-06-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200629_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good'), ('LG', 'Lawful Good'), ('CE', 'Chaotic Evil'), ('CN', 'Chaotic Neutral'), ('NG', 'Neutral Good'), ('NN', 'True Neutral'), ('NE', 'Neutral Evil'), ('LE', 'Lawful Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='class',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='race',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('FEET', 'Feet'), ('EYE', 'Eye'), ('LEGS', 'Legs'), ('HEAD', 'Head'), ('NECK', 'Neck'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
    ]
