# Generated by Django 2.2.12 on 2020-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20200626_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CE', 'Chaotic Evil'), ('CN', 'Chaotic Neutral'), ('LN', 'Lawful Neutral'), ('NE', 'Neutral Evil'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LG', 'Lawful Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('FEET', 'Feet'), ('TORSO', 'Torso'), ('EYE', 'Eye'), ('LEGS', 'Legs')], max_length=50),
        ),
    ]
