# Generated by Django 2.2.12 on 2020-06-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200629_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CG', 'Chaotic Good'), ('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CE', 'Chaotic Evil'), ('LN', 'Lawful Neutral'), ('NN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('TORSO', 'Torso'), ('HEAD', 'Head'), ('EYE', 'Eye'), ('FEET', 'Feet'), ('LEGS', 'Legs'), ('NECK', 'Neck')], max_length=50),
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ManyToManyField(blank=True, to='player.Language'),
        ),
    ]
