# Generated by Django 2.2.12 on 2020-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200703_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='ac',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CN', 'Chaotic Neutral'), ('NN', 'True Neutral'), ('LG', 'Lawful Good'), ('CE', 'Chaotic Evil'), ('CG', 'Chaotic Good'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('NE', 'Neutral Evil'), ('LN', 'Lawful Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('TORSO', 'Torso'), ('EYE', 'Eye'), ('LEGS', 'Legs'), ('FEET', 'Feet'), ('HEAD', 'Head'), ('NECK', 'Neck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
    ]
