# Generated by Django 2.2.12 on 2020-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200706_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NN', 'True Neutral'), ('LE', 'Lawful Evil'), ('CE', 'Chaotic Evil'), ('NG', 'Neutral Good'), ('LG', 'Lawful Good'), ('NE', 'Neutral Evil'), ('CN', 'Chaotic Neutral'), ('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('EYE', 'Eye'), ('FEET', 'Feet'), ('TORSO', 'Torso'), ('LEGS', 'Legs')], max_length=50),
        ),
    ]
