# Generated by Django 2.2.12 on 2020-06-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200629_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='eyes',
            field=models.CharField(blank=True, default='Green', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='hair',
            field=models.CharField(blank=True, default='Blonde', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pc',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CE', 'Chaotic Evil'), ('NN', 'True Neutral'), ('NE', 'Neutral Evil'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('NG', 'Neutral Good'), ('LE', 'Lawful Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('LEGS', 'Legs'), ('EYE', 'Eye'), ('FEET', 'Feet'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
