# Generated by Django 2.2.12 on 2020-06-22 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200622_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='playerName',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good'), ('NE', 'Neutral Evil'), ('LG', 'Lawful Good'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil'), ('NG', 'Neutral Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
    ]
