# Generated by Django 2.2.12 on 2020-06-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20200622_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NG', 'Neutral Good'), ('CN', 'Chaotic Neutral'), ('LG', 'Lawful Good'), ('LE', 'Lawful Evil'), ('CE', 'Chaotic Evil'), ('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good'), ('NE', 'Neutral Evil'), ('NN', 'True Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
    ]
