# Generated by Django 2.2.12 on 2020-06-23 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20200622_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(choices=[('F', 'Fine'), ('D', 'Diminutive'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('H', 'Huge'), ('G', 'Gargantuan'), ('C', 'Colossal')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NE', 'Neutral Evil'), ('CN', 'Chaotic Neutral'), ('NG', 'Neutral Good'), ('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good'), ('NN', 'True Neutral'), ('LE', 'Lawful Evil'), ('CE', 'Chaotic Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='race',
            name='abilities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Abilities'),
        ),
    ]
