# Generated by Django 2.2.12 on 2020-06-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20200623_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NG', 'Neutral Good'), ('LN', 'Lawful Neutral'), ('LG', 'Lawful Good'), ('NN', 'True Neutral'), ('CG', 'Chaotic Good'), ('NE', 'Neutral Evil'), ('LE', 'Lawful Evil'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
