# Generated by Django 2.2.12 on 2020-06-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_auto_20200623_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='classLevels',
            field=models.ManyToManyField(blank=True, to='player.ClassLevel'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NN', 'True Neutral'), ('LN', 'Lawful Neutral'), ('CE', 'Chaotic Evil'), ('CG', 'Chaotic Good'), ('LE', 'Lawful Evil'), ('CN', 'Chaotic Neutral'), ('NG', 'Neutral Good'), ('LG', 'Lawful Good'), ('NE', 'Neutral Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
    ]
