# Generated by Django 2.2.12 on 2020-06-23 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20200623_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='shortHand',
            field=models.CharField(default='clr', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good'), ('CE', 'Chaotic Evil'), ('NN', 'True Neutral'), ('NG', 'Neutral Good'), ('CN', 'Chaotic Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
