# Generated by Django 2.2.12 on 2020-06-25 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_auto_20200623_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='fort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effect',
            name='ref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='effect',
            name='will',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='fort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='ref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='will',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='constitution',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='wisdom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CN', 'Chaotic Neutral'), ('NE', 'Neutral Evil'), ('LG', 'Lawful Good'), ('LE', 'Lawful Evil'), ('CE', 'Chaotic Evil'), ('LN', 'Lawful Neutral'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('NN', 'True Neutral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='pcskillrank',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillRanks', to='player.PC'),
        ),
    ]
