# Generated by Django 2.2.12 on 2020-06-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_auto_20200625_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='needsAmo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CN', 'Chaotic Neutral'), ('LN', 'Lawful Neutral'), ('LG', 'Lawful Good'), ('NN', 'True Neutral'), ('CG', 'Chaotic Good'), ('CE', 'Chaotic Evil'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('NE', 'Neutral Evil')], max_length=2),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='specialAbilities',
            field=models.ManyToManyField(blank=True, to='player.SpecialAbilities'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Head'), ('EYE', 'Eye'), ('NECK', 'Neck'), ('LEGS', 'Legs'), ('FEET', 'Feet'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
    ]
