# Generated by Django 2.2.12 on 2020-06-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20200626_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='needsAmo',
            new_name='needsAmmo',
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('CE', 'Chaotic Evil'), ('CN', 'Chaotic Neutral'), ('NN', 'True Neutral'), ('LG', 'Lawful Good'), ('NE', 'Neutral Evil'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='carriedEquipment',
            field=models.ManyToManyField(blank=True, to='player.Inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.Inventory'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('EYE', 'Eye'), ('TORSO', 'Torso'), ('FEET', 'Feet'), ('LEGS', 'Legs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
