# Generated by Django 2.2.12 on 2020-06-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_auto_20200626_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmmoType',
            fields=[
                ('type', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='defualtAmmo',
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NE', 'Neutral Evil'), ('LG', 'Lawful Good'), ('CN', 'Chaotic Neutral'), ('NG', 'Neutral Good'), ('CE', 'Chaotic Evil'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('LN', 'Lawful Neutral'), ('CG', 'Chaotic Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('FEET', 'Feet'), ('LEGS', 'Legs'), ('EYE', 'Eye'), ('HEAD', 'Head'), ('TORSO', 'Torso'), ('NECK', 'Neck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('1H', 'One Handed'), ('2H', 'Two Handed')], max_length=2),
        ),
        migrations.AddField(
            model_name='ammo',
            name='ammoType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.AmmoType'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='defaultAmmoType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.AmmoType'),
        ),
    ]
