# Generated by Django 2.2.12 on 2020-06-26 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20200626_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('NE', 'Neutral Evil'), ('LE', 'Lawful Evil'), ('NN', 'True Neutral'), ('LN', 'Lawful Neutral'), ('CN', 'Chaotic Neutral'), ('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CE', 'Chaotic Evil'), ('CG', 'Chaotic Good')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='carriedEquipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='carriedEquipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Inventory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='effects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Effect'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('LEGS', 'Legs'), ('FEET', 'Feet'), ('HEAD', 'Head'), ('EYE', 'Eye'), ('NECK', 'Neck'), ('TORSO', 'Torso')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
