# Generated by Django 2.2.12 on 2020-06-26 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_auto_20200626_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eyes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eyes', to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='feet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feet', to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='legs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='player.InventoryItem'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='neck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neck', to='player.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='alignment',
            name='alignment',
            field=models.CharField(choices=[('LN', 'Lawful Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('CE', 'Chaotic Evil'), ('NN', 'True Neutral'), ('NE', 'Neutral Evil'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LG', 'Lawful Good')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='player.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='leftHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leftHanded', to='player.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rightHand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='righthanded', to='player.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='race',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='player.SelectedRace'),
        ),
        migrations.AlterField(
            model_name='wearableitem',
            name='area',
            field=models.CharField(choices=[('TORSO', 'Torso'), ('EYE', 'Eye'), ('HEAD', 'Head'), ('LEGS', 'Legs'), ('NECK', 'Neck'), ('FEET', 'Feet')], max_length=50),
        ),
        migrations.AlterField(
            model_name='wieldableitem',
            name='area',
            field=models.CharField(choices=[('2H', 'Two Handed'), ('1H', 'One Handed')], max_length=2),
        ),
    ]
